# Generated by Django 4.2.16 on 2025-08-20 03:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import ndas.custom_codes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dr. Rasika Kulasinghe', help_text="Developer's full name", max_length=100, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, help_text="Developer's logo or photo", upload_to='developer_logos/%Y/%m/', validators=[ndas.custom_codes.validators.image_extension_validation], verbose_name='Logo/Photo')),
                ('qualifications', models.CharField(default='MBBS, HDIT, BIT', help_text='Professional qualifications', max_length=500, verbose_name='Qualifications')),
                ('email', models.EmailField(default='rasikakulasinghe@gmail.com', help_text='Contact email address', max_length=45, verbose_name='Email')),
                ('mobile_phone', models.CharField(blank=True, help_text='Mobile phone number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Phone')),
                ('landline_phone', models.CharField(blank=True, help_text='Landline phone number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Landline Phone')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL', verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL', verbose_name='Twitter')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='WhatsApp')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL', verbose_name='YouTube')),
                ('website_url', models.URLField(blank=True, help_text='Personal or professional website URL', verbose_name='Website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Developer Contact',
                'verbose_name_plural': 'Developer Contacts',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='DevoloperContacts',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_home',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_station',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='other',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='possition',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tp_lan_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tp_lan_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tp_mobile_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tp_mobile_2',
        ),
        migrations.AddField(
            model_name='customuser',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Additional notes or information', verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='home_address',
            field=models.TextField(blank=True, help_text='Home address', verbose_name='Home Address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='landline_primary',
            field=models.CharField(blank=True, help_text='Primary landline number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Primary Landline'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='landline_secondary',
            field=models.CharField(blank=True, help_text='Secondary landline number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Secondary Landline'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_primary',
            field=models.CharField(default=django.utils.timezone.now, help_text='Primary mobile number (required)', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Primary Mobile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_secondary',
            field=models.CharField(blank=True, help_text='Secondary mobile number (optional)', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Secondary Mobile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Medical Officer', 'Medical Officer'), ('Consultant', 'Consultant'), ('Registrar', 'Registrar'), ('Physiotherapist', 'Physiotherapist'), ('Occupational Therapist', 'Occupational Therapist'), ('Administrator', 'Administrator'), ('Nursing officer', 'Nursing officer'), ('Senior Registrar', 'Senior Registrar')], default='Medical Officer', help_text="User's professional position", max_length=30, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (JPG, JPEG, PNG only)', upload_to='profile_pictures/%Y/%m/', validators=[ndas.custom_codes.validators.image_extension_validation], verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='station_address',
            field=models.TextField(blank=True, help_text='Work station address', verbose_name='Station Address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login_device',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='Last device used for login', max_length=255, verbose_name='Last Login Device'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['position'], name='users_custo_positio_e363bb_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='users_custo_created_f4b145_idx'),
        ),
    ]
