# Generated by Django 4.1.6 on 2025-11-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="developercontacts",
            name="linkedin_url",
            field=models.URLField(
                blank=True, help_text="LinkedIn profile URL", verbose_name="LinkedIn"
            ),
        ),
    ]
