# Generated by Django 4.2.7 on 2025-11-09 15:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_linkedin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At')),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', help_text='Type of subscription (Free or Paid)', max_length=10, verbose_name='Subscription Type')),
                ('start_date', models.DateField(db_index=True, help_text='Subscription start date', verbose_name='Start Date')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Subscription duration in days', verbose_name='Duration (Days)')),
                ('billing_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Billing amount for this subscription period', max_digits=10, verbose_name='Billing Amount')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('grace_period', 'Grace Period')], db_index=True, default='active', help_text='Current subscription status', max_length=15, verbose_name='Status')),
                ('grace_period_days', models.PositiveIntegerField(default=7, help_text='Number of days for grace period after expiration', verbose_name='Grace Period (Days)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks about this subscription', verbose_name='Notes')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_added', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('last_edit_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By')),
                ('user', models.OneToOneField(help_text='User associated with this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_subsc_user_id_877733_idx'), models.Index(fields=['start_date'], name='users_subsc_start_d_0304bd_idx'), models.Index(fields=['status'], name='users_subsc_status_f062c3_idx')],
            },
        ),
    ]
