# Generated by Django 4.2.7 on 2025-11-09 15:10

from django.db import migrations
from datetime import date
from decimal import Decimal


def create_default_subscriptions(apps, schema_editor):
    """
    Create default Free subscriptions for all existing users without subscriptions.
    Default: 30-day duration, 7-day grace period, start_date=migration date.
    """
    CustomUser = apps.get_model('users', 'CustomUser')
    Subscription = apps.get_model('users', 'Subscription')
    
    users_without_subscription = CustomUser.objects.filter(subscription__isnull=True)
    
    subscriptions_to_create = []
    today = date.today()
    
    for user in users_without_subscription:
        subscriptions_to_create.append(
            Subscription(
                user=user,
                subscription_type='free',
                start_date=today,
                duration_days=30,
                billing_amount=Decimal('0.00'),
                status='active',
                grace_period_days=7,
                notes='Default subscription created during migration',
            )
        )
    
    if subscriptions_to_create:
        Subscription.objects.bulk_create(subscriptions_to_create)


def reverse_default_subscriptions(apps, schema_editor):
    """
    Remove default subscriptions created during migration.
    """
    Subscription = apps.get_model('users', 'Subscription')
    Subscription.objects.filter(
        notes='Default subscription created during migration'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription'),
    ]

    operations = [
        migrations.RunPython(
            create_default_subscriptions,
            reverse_default_subscriptions,
        ),
    ]
