# Generated by Django 4.1.6 on 2025-08-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useractivitylog_usersession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='browser_name',
            field=models.CharField(blank=True, default='Unknown', help_text='Browser name (Chrome, Firefox, etc.)', max_length=100, verbose_name='Browser Name'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='browser_version',
            field=models.CharField(blank=True, default='Unknown', help_text='Browser version', max_length=50, verbose_name='Browser Version'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='device_brand',
            field=models.CharField(blank=True, default='Unknown', help_text='Device brand (Apple, Samsung, etc.)', max_length=100, verbose_name='Device Brand'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='device_model',
            field=models.CharField(blank=True, default='Unknown', help_text='Device model', max_length=100, verbose_name='Device Model'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='device_type',
            field=models.CharField(blank=True, default='Unknown', help_text='Device type (Desktop, Mobile, Tablet)', max_length=50, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='operating_system',
            field=models.CharField(blank=True, default='Unknown', help_text='Operating system (Windows, macOS, Linux, etc.)', max_length=100, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Full user agent string', verbose_name='User Agent'),
        ),
    ]
