# Generated by Django 4.2.16 on 2025-08-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_field_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='session_key',
            field=models.CharField(blank=True, default='', help_text='Django session key', max_length=40, verbose_name='Session Key'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(default='', help_text='Django session key', max_length=40, unique=True, verbose_name='Session Key'),
        ),
    ]
