# Generated by Django 4.1.6 on 2025-11-09 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_default_subscriptions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Global Subscription",
                "verbose_name_plural": "Global Subscription",
            },
        ),
        migrations.RemoveIndex(
            model_name="subscription",
            name="users_subsc_user_id_877733_idx",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="user",
        ),
    ]
