# Generated by Django 4.1.6 on 2025-08-22 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ndas.custom_codes.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_useractivitylog_session_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="developercontacts",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="developercontacts",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="When this record was created",
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When this record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When this record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When this record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="landline_primary",
            field=models.CharField(
                blank=True,
                help_text="Primary landline number",
                max_length=15,
                validators=[ndas.custom_codes.validators.validate_phone_number],
                verbose_name="Primary Landline",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="landline_secondary",
            field=models.CharField(
                blank=True,
                help_text="Secondary landline number",
                max_length=15,
                validators=[ndas.custom_codes.validators.validate_phone_number],
                verbose_name="Secondary Landline",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobile_primary",
            field=models.CharField(
                help_text="Primary mobile number (required)",
                max_length=15,
                validators=[ndas.custom_codes.validators.validate_phone_number],
                verbose_name="Primary Mobile",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobile_secondary",
            field=models.CharField(
                blank=True,
                help_text="Secondary mobile number (optional)",
                max_length=15,
                validators=[ndas.custom_codes.validators.validate_phone_number],
                verbose_name="Secondary Mobile",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When this record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="developercontacts",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When this record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="developercontacts",
            name="landline_phone",
            field=models.CharField(
                blank=True,
                help_text="Landline phone number",
                max_length=15,
                validators=[ndas.custom_codes.validators.validate_phone_number],
                verbose_name="Landline Phone",
            ),
        ),
        migrations.AlterField(
            model_name="developercontacts",
            name="mobile_phone",
            field=models.CharField(
                blank=True,
                help_text="Mobile phone number",
                max_length=15,
                validators=[ndas.custom_codes.validators.validate_phone_number],
                verbose_name="Mobile Phone",
            ),
        ),
        migrations.AlterField(
            model_name="developercontacts",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When this record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="developercontacts",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp number",
                max_length=15,
                validators=[ndas.custom_codes.validators.validate_phone_number],
                verbose_name="WhatsApp",
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When this record was created",
                verbose_name="Created At",
            ),
        ),
    ]
