# Generated by Django 4.1.6 on 2025-11-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_paid_to_commercial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=[("free", "Free"), ("commercial", "Commercial")],
                default="free",
                help_text="Type of subscription (Free or Commercial)",
                max_length=10,
                verbose_name="Subscription Type",
            ),
        ),
    ]
