# Generated by Django 6.0 on 2025-12-25 13:25

import ndas.custom_codes.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_subscription_subscription_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="mobile_primary",
            field=models.CharField(
                db_index=True,
                help_text="Primary mobile number (required)",
                max_length=15,
                validators=[ndas.custom_codes.validators.validate_phone_number],
                verbose_name="Primary Mobile",
            ),
        ),
    ]
