# Generated by Django 6.0 on 2026-02-24 17:47

import django.db.models.deletion
from django.db import migrations, models


def set_superadmin_user_type(apps, schema_editor):
    """Set user_type=SUPERADMIN for all existing is_superuser=True users."""
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(is_superuser=True).update(user_type='SUPERADMIN')


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0001_initial"),
        ("users", "0008_alter_customuser_mobile_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Bound institution. Null only for SUPERADMIN. Populated by Story 1.6 data migration for existing users.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="institution.institution",
                verbose_name="Institution",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "Super Admin"),
                    ("ADMIN", "Institution Admin"),
                    ("USER", "Clinician"),
                ],
                db_index=True,
                default="USER",
                help_text="User role type: SUPERADMIN has system-wide access; ADMIN manages own institution; USER is a clinician",
                max_length=20,
                verbose_name="User Type",
            ),
        ),
        migrations.RunPython(
            set_superadmin_user_type,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
