version: "3.8" # We need to define the docker specification version
services: # Define our service(s) - in this case we only have one 
  app: # We will build a singular app 
    build: . # Used to build our dockerfile
    volumes: # This refers to our directory that we defined /djangoapp
      - .:/ndas
    ports: # We want to expose port 8000 within our container
      - 8000:8000
    image: ndas:django # Tag/add our docker image name
    container_name: ndas_container # Specify a container name
    command: gunicorn ndas.wsgi:application --timeout 0 --bind 0.0.0.0:8000 # Expose all IP addresses to connect to port 8000