# Generated by Django 6.0 on 2026-02-26 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0004_institution_logo_path_callable"),
        ("referral", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("REFERRAL_RECEIVED", "Referral Received"),
                            ("REFERRAL_REPLIED", "Referral Replied"),
                            ("REFERRAL_CLOSED", "Referral Closed"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("link", models.CharField(blank=True, max_length=500)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="referralreceived",
            new_name="referral_re_referra_6e53d6_idx",
            old_name="referral_re_referra_rec_idx",
        ),
        migrations.RenameIndex(
            model_name="referralreceived",
            new_name="referral_re_to_inst_2b9c71_idx",
            old_name="referral_re_to_inst_rec_idx",
        ),
        migrations.RenameIndex(
            model_name="referralsent",
            new_name="referral_re_referra_c0f6f7_idx",
            old_name="referral_re_referra_idx",
        ),
        migrations.RenameIndex(
            model_name="referralsent",
            new_name="referral_re_from_in_9b3988_idx",
            old_name="referral_re_from_in_idx",
        ),
        migrations.RenameIndex(
            model_name="referralsent",
            new_name="referral_re_to_inst_e80402_idx",
            old_name="referral_re_to_inst_idx",
        ),
        migrations.AlterField(
            model_name="referralmessage",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AlterField(
            model_name="referralmessage",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AlterField(
            model_name="referralreceived",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AlterField(
            model_name="referralreceived",
            name="is_read",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True once the receiving clinician has opened the referral thread.",
            ),
        ),
        migrations.AlterField(
            model_name="referralreceived",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AlterField(
            model_name="referralreceived",
            name="referral_uuid",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                help_text="Copied from ReferralSent.referral_uuid. Never regenerated.",
            ),
        ),
        migrations.AlterField(
            model_name="referralreceived",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("REPLIED", "Replied"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="referralsent",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AlterField(
            model_name="referralsent",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AlterField(
            model_name="referralsent",
            name="referral_uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Shared with ReferralReceived. Generated once at creation; never regenerated.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="referralsent",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("REPLIED", "Replied"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
