# Generated by Django 6.0 on 2026-09-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referral", "0002_notification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("REFERRAL_RECEIVED", "Referral Received"),
                    ("REFERRAL_REPLIED", "Referral Replied"),
                    ("REFERRAL_CLOSED", "Referral Closed"),
                    ("BACKUP_COMPLETED", "Backup Completed"),
                    ("BACKUP_FAILED", "Backup Failed"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
