# Generated by Django 6.0 on 2026-09-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REFERRAL_RECEIVED', 'Referral Received'), ('REFERRAL_REPLIED', 'Referral Replied'), ('REFERRAL_CLOSED', 'Referral Closed'), ('BACKUP_COMPLETED', 'Backup Completed'), ('BACKUP_FAILED', 'Backup Failed'), ('RESTORE_COMPLETED', 'Restore Completed'), ('RESTORE_FAILED', 'Restore Failed')], db_index=True, max_length=30),
        ),
    ]
