"""
Security tests for reports app.

Covers: AC 1 (Fix #1 IDOR), AC 15/16 (Fix #14 report ownership),
cross-tenant Excel export scoping (spec-fix-cross-tenant-data-leaks).
"""
import os
import shutil
import tempfile
import uuid
from unittest.mock import patch

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.test import Client, TestCase, override_settings
from django.urls import reverse
from django.utils import timezone

from institution.models import Institution
from patients.models import (
    CDICRecord, DevelopmentalAssessment, GeneralPaediatricAssessment,
    GMAssessment, HINEAssessment, Patient,
)
from video.models import Video

User = get_user_model()

STATIC_OVERRIDE = override_settings(
    STORAGES={
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    },
    MULTI_INSTITUTION_ENABLED=True,
    RATELIMIT_ENABLE=False,
)


class ReportSecurityBase(TestCase):
    """Shared setup for report security tests."""

    def setUp(self):
        self.client = Client()
        self.inst_a = Institution.objects.create(name='Hospital A', slug='hosp-a')
        self.inst_b = Institution.objects.create(name='Hospital B', slug='hosp-b')

        self.superuser = User.objects.create_superuser(
            username='super', password='SuperPass123!', email='super@test.com',
            mobile_primary='0700000001',
        )
        self.staff_a = User.objects.create_user(
            username='staff_a', password='StaffPass123!', email='staff_a@test.com',
            is_staff=True, institution=self.inst_a, mobile_primary='0700000002',
        )
        self.staff_b = User.objects.create_user(
            username='staff_b', password='StaffPass123!', email='staff_b@test.com',
            is_staff=True, institution=self.inst_b, mobile_primary='0700000003',
        )

        # Patient at inst_b (belongs to the "wrong" institution for staff_a)
        self.patient_b = Patient.objects.create(
            bht='BHT-SEC-B-001',
            baby_name='Sec Baby B',
            mother_name='Sec Mother B',
            gender='Male',
            dob_tob=timezone.now() - timezone.timedelta(days=30),
            mo_delivery='Normal vaginal delivery (NVD)',
            pog_wks=38,
            pog_days=0,
            birth_weight=3000,
            ofc=34,
            tp_mobile='0771234567',
            institution=self.inst_b,
        )
        # Use bulk_create to bypass Video.save() which calls video_file.size on real storage
        self.video_b = Video.objects.bulk_create([Video(
            patient=self.patient_b,
            title='SecVideo',
            video_file='videos/dummy_b.mp4',
            recorded_on=timezone.now(),
        )])[0]
        self.assessment_b = GMAssessment.objects.create(
            patient=self.patient_b,
            video_file=self.video_b,
            date_of_assessment=timezone.now(),
        )


@STATIC_OVERRIDE
class IDORPDFDownloadTest(ReportSecurityBase):
    """AC 1: Cross-institution IDOR on GM assessment PDF → 404."""

    def test_cross_institution_gm_pdf_returns_404(self):
        """Staff from inst_a cannot download a GM assessment PDF for inst_b patient."""
        self.client.force_login(self.staff_a)
        url = reverse('reports:pdf-gm', kwargs={'assessment_id': self.assessment_b.id})
        response = self.client.get(url)
        self.assertEqual(response.status_code, 404)

    def test_superuser_can_access_any_institution_gm_pdf(self):
        """Superuser bypasses institution scope — assessment lookup succeeds (not 404)."""
        # Use raise_request_exception=False so a generator error returns 500, not a test failure
        client = Client(raise_request_exception=False)
        client.force_login(self.superuser)
        url = reverse('reports:pdf-gm', kwargs={'assessment_id': self.assessment_b.id})
        with patch('reports.views.GMAssessmentPDFGenerator') as mock_gen:
            mock_instance = mock_gen.return_value
            mock_instance.generate.side_effect = Exception('no pdf in test')
            response = client.get(url)
        # Superuser should reach PDF generation (not get 404 from institution scope)
        self.assertNotEqual(response.status_code, 404)


@STATIC_OVERRIDE
class ReportOwnershipTest(ReportSecurityBase):
    """AC 15/16: Report download ownership via session-keyed cache."""

    def _valid_file_id(self):
        return f"{uuid.uuid4()}.xlsx"

    def test_cross_session_download_denied(self):
        """AC 15: User B cannot download a report generated by User A."""
        self.client.force_login(self.staff_a)
        # Simulate staff_a generating a report by setting the cache key
        file_id = self._valid_file_id()
        session_key_a = self.client.session.session_key
        if not session_key_a:
            self.client.session.save()
            session_key_a = self.client.session.session_key
        cache.set(f"report_owner_{file_id}_{session_key_a}", self.staff_a.pk, 86400)

        # staff_b in a different session tries to download
        client_b = Client()
        client_b.force_login(self.staff_b)
        url = reverse('reports:download', kwargs={'file_id': file_id})
        response = client_b.get(url)
        self.assertEqual(response.status_code, 403)

    def test_own_report_download_passes_ownership_check(self):
        """AC 16: A user's own report passes the ownership check — response is not 403."""
        self.client.force_login(self.staff_a)
        session = self.client.session
        if not session.session_key:
            session.save()
        session_key = session.session_key

        file_id = self._valid_file_id()
        cache.set(f"report_owner_{file_id}_{session_key}", self.staff_a.pk, 86400)

        url = reverse('reports:download', kwargs={'file_id': file_id})
        response = self.client.get(url)
        # File doesn't exist on disk → 404, but ownership check passed (not 403)
        self.assertEqual(response.status_code, 404)
        self.assertNotEqual(response.status_code, 403)

    def test_cross_session_delete_denied(self):
        """User B cannot delete a report generated by User A."""
        self.client.force_login(self.staff_a)
        file_id = self._valid_file_id()
        session_key_a = self.client.session.session_key
        if not session_key_a:
            self.client.session.save()
            session_key_a = self.client.session.session_key
        cache.set(f"report_owner_{file_id}_{session_key_a}", self.staff_a.pk, 86400)

        client_b = Client()
        client_b.force_login(self.staff_b)
        url = reverse('reports:delete', kwargs={'file_id': file_id})
        response = client_b.post(url)
        self.assertEqual(response.status_code, 403)
        self.assertFalse(response.json()['success'])

    def test_own_report_delete_passes_ownership_check(self):
        """A user's own report passes the ownership check on delete — response is not 403."""
        self.client.force_login(self.staff_a)
        session = self.client.session
        if not session.session_key:
            session.save()
        session_key = session.session_key

        file_id = self._valid_file_id()
        cache.set(f"report_owner_{file_id}_{session_key}", self.staff_a.pk, 86400)

        url = reverse('reports:delete', kwargs={'file_id': file_id})
        response = self.client.post(url)
        # File doesn't exist on disk → 404 "not found", but ownership check passed (not 403)
        self.assertEqual(response.status_code, 404)
        self.assertNotEqual(response.status_code, 403)

    def test_report_history_excludes_other_users_reports(self):
        """report_history only lists reports owned by the requesting user's session."""
        temp_dir = os.path.join(settings.MEDIA_ROOT, 'reports', 'temp')
        os.makedirs(temp_dir, exist_ok=True)

        self.client.force_login(self.staff_a)
        session = self.client.session
        if not session.session_key:
            session.save()
        session_key = session.session_key

        own_file_id = self._valid_file_id()
        other_file_id = self._valid_file_id()
        own_path = os.path.join(temp_dir, own_file_id)
        other_path = os.path.join(temp_dir, other_file_id)
        self.addCleanup(lambda: os.path.exists(own_path) and os.remove(own_path))
        self.addCleanup(lambda: os.path.exists(other_path) and os.remove(other_path))
        for path in (own_path, other_path):
            with open(path, 'wb') as f:
                f.write(b'dummy')

        # Only the "own" file has a matching cache-owner entry for this session.
        cache.set(f"report_owner_{own_file_id}_{session_key}", self.staff_a.pk, 86400)

        url = reverse('reports:history')
        response = self.client.get(url)
        filenames = [r['filename'] for r in response.context['reports']]
        self.assertIn(own_file_id, filenames)
        self.assertNotIn(other_file_id, filenames)


@STATIC_OVERRIDE
class ExcelExportInstitutionScopingTest(TestCase):
    """
    spec-fix-cross-tenant-data-leaks: ExcelReportGenerator.generate(institution=...)
    must scope all six sheet types (patients + 5 assessment types) to the given
    institution, instead of leaking every institution's data.
    """

    def setUp(self):
        self.inst_a = Institution.objects.create(name='Excel Hospital A', slug='excel-hosp-a')
        self.inst_b = Institution.objects.create(name='Excel Hospital B', slug='excel-hosp-b')

        self.staff_a = User.objects.create_user(
            username='excel_staff_a', password='StaffPass123!', email='excel_a@test.com',
            is_staff=True, institution=self.inst_a, mobile_primary='0700000010',
        )

        common_patient_fields = dict(
            mother_name='Test Mother',
            gender='Male',
            dob_tob=timezone.now() - timezone.timedelta(days=60),
            mo_delivery='Normal vaginal delivery (NVD)',
            pog_wks=38,
            pog_days=0,
            birth_weight=3000,
            ofc=34,
            tp_mobile='0771234567',
        )
        # Institution A gets TWO patients, institution B gets ONE — deliberately
        # asymmetric so a mis-scoped filter (e.g. inverted, or scoped to the
        # wrong institution) produces a distinguishable count instead of
        # silently matching by coincidence, as it would with a symmetric 1:1 split.
        self.patient_a = Patient.objects.create(
            bht='BHT-EXCEL-A-001', baby_name='Excel Baby A',
            institution=self.inst_a, **common_patient_fields,
        )
        self.patient_a2 = Patient.objects.create(
            bht='BHT-EXCEL-A-002', baby_name='Excel Baby A2',
            institution=self.inst_a, **common_patient_fields,
        )
        self.patient_b = Patient.objects.create(
            bht='BHT-EXCEL-B-001', baby_name='Excel Baby B',
            institution=self.inst_b, **common_patient_fields,
        )

        # Videos required for GMAssessment — bulk_create bypasses Video.save()'s
        # real-storage .size access (same pattern as ReportSecurityBase above).
        self.video_a, self.video_a2, self.video_b = Video.objects.bulk_create([
            Video(patient=self.patient_a, title='ExcelVideoA',
                  video_file='videos/excel_dummy_a.mp4', recorded_on=timezone.now()),
            Video(patient=self.patient_a2, title='ExcelVideoA2',
                  video_file='videos/excel_dummy_a2.mp4', recorded_on=timezone.now()),
            Video(patient=self.patient_b, title='ExcelVideoB',
                  video_file='videos/excel_dummy_b.mp4', recorded_on=timezone.now()),
        ])

        now = timezone.now()
        today = now.date()

        for patient, video in (
            (self.patient_a, self.video_a),
            (self.patient_a2, self.video_a2),
            (self.patient_b, self.video_b),
        ):
            GMAssessment.objects.create(
                patient=patient, video_file=video, date_of_assessment=now,
            )
            HINEAssessment.objects.create(
                patient=patient, date_of_assessment=now, score=70,
                assessment_done_by='Dr. Test',
            )
            DevelopmentalAssessment.objects.create(
                patient=patient, date_of_assessment=now,
            )
            CDICRecord.objects.create(
                patient=patient, assessment_date=today,
            )
            GeneralPaediatricAssessment.objects.create(
                patient=patient, assessment_date=now,
                healthcare_provider='Dr. Test',
                current_problems='None', physical_examination='Normal',
                investigation_summary='N/A', prescribed_medications='None',
                next_plan='Routine follow-up',
            )

        self._tmp_dir = tempfile.mkdtemp(prefix='ndas_excel_test_')
        self.addCleanup(lambda: shutil.rmtree(self._tmp_dir, ignore_errors=True))

    def _generate(self, institution):
        from reports.utils.excel_generator import ExcelReportGenerator

        generator = ExcelReportGenerator()
        output_path = os.path.join(self._tmp_dir, f'{uuid.uuid4()}.xlsx')
        parameters = {
            'patients': True,
            'gm_assessments': True,
            'hine_assessments': True,
            'developmental_assessments': True,
            'cdic_records': True,
            'gpa_assessments': True,
        }
        _, metadata = generator.generate(
            output_path=output_path, parameters=parameters, institution=institution,
        )
        return metadata

    def test_institution_scoped_export_excludes_other_institution(self):
        """
        Given institution=A (2 patients), every sheet returns exactly 2 records —
        never institution B's 1. The asymmetric 2-vs-1 split means an inverted
        filter (e.g. .exclude() instead of .filter(), or a filter scoped to the
        wrong institution variable) would yield 1, not 2, so it can't pass by
        coincidence the way a symmetric 1-vs-1 fixture could.
        """
        metadata = self._generate(self.inst_a)
        sheets = metadata['sheets']
        self.assertEqual(sheets['Patients'], 2, "Both of institution A's patients must appear")
        self.assertEqual(sheets['GM Assessments'], 2)
        self.assertEqual(sheets['HINE Assessments'], 2)
        self.assertEqual(sheets['Developmental Assessments'], 2)
        self.assertEqual(sheets['CDIC Records'], 2)
        self.assertEqual(sheets['GPA Assessments'], 2)

    def test_institution_b_scoped_export_returns_only_its_own_record(self):
        """
        Given institution=B (1 patient), every sheet returns exactly 1 record —
        never institution A's 2. Pins down that scoping tracks whichever
        institution is actually passed in, not just "institution A vs unfiltered".
        """
        metadata = self._generate(self.inst_b)
        sheets = metadata['sheets']
        self.assertEqual(sheets['Patients'], 1, "Only institution B's patient must appear")
        self.assertEqual(sheets['GM Assessments'], 1)
        self.assertEqual(sheets['HINE Assessments'], 1)
        self.assertEqual(sheets['Developmental Assessments'], 1)
        self.assertEqual(sheets['CDIC Records'], 1)
        self.assertEqual(sheets['GPA Assessments'], 1)

    def test_none_institution_export_stays_unfiltered(self):
        """Phase-1 backward compat: institution=None must remain unfiltered (all 3 patients)."""
        metadata = self._generate(None)
        sheets = metadata['sheets']
        self.assertEqual(sheets['Patients'], 3, "Unscoped export must include both institutions")
        self.assertEqual(sheets['GM Assessments'], 3)
        self.assertEqual(sheets['HINE Assessments'], 3)
        self.assertEqual(sheets['Developmental Assessments'], 3)
        self.assertEqual(sheets['CDIC Records'], 3)
        self.assertEqual(sheets['GPA Assessments'], 3)


@STATIC_OVERRIDE
class ExcelFormulaInjectionTest(TestCase):
    """
    Regression test for spreadsheet formula injection: a patient free-text
    field starting with =/+/-/@ must be escaped (leading single-quote) in
    the exported .xlsx, not stored as a live formula.
    """

    def setUp(self):
        self.inst = Institution.objects.create(name='Formula Test Hospital', slug='formula-test-hosp')
        self.patient = Patient.objects.create(
            bht='BHT-FORMULA-001',
            baby_name='=HYPERLINK("http://evil.example/",A1)',
            mother_name='+1+1',
            nnc_no='-2+3',
            gender='Male',
            dob_tob=timezone.now() - timezone.timedelta(days=10),
            mo_delivery='Normal vaginal delivery (NVD)',
            pog_wks=38, pog_days=0, birth_weight=3000, ofc=34,
            tp_mobile='0771234567',
            institution=self.inst,
        )
        self._tmp_dir = tempfile.mkdtemp(prefix='ndas_excel_formula_test_')
        self.addCleanup(lambda: shutil.rmtree(self._tmp_dir, ignore_errors=True))

    def test_malicious_patient_fields_are_escaped_in_exported_cells(self):
        """End-to-end round trip through real openpyxl write+read for all four
        formula-triggering leading characters (=, +, -, @ is covered at the
        unit level in EscapeExcelFormulaTest)."""
        from openpyxl import load_workbook
        from reports.utils.excel_generator import ExcelReportGenerator

        generator = ExcelReportGenerator()
        output_path = os.path.join(self._tmp_dir, f'{uuid.uuid4()}.xlsx')
        generator.generate(
            output_path=output_path,
            parameters={'patients': True},
            institution=self.inst,
        )

        wb = load_workbook(output_path)
        ws = wb['Patients']
        headers = [c.value for c in ws[1]]
        row = ws[2]

        def cell(header):
            return row[headers.index(header)].value

        baby_name_cell = cell('Baby Name')
        mother_name_cell = cell('Mother Name')
        nnc_no_cell = cell('NNC')

        self.assertTrue(
            baby_name_cell.startswith("'="),
            f"Expected leading-quote-escaped formula, got: {baby_name_cell!r}",
        )
        self.assertIn('HYPERLINK', baby_name_cell)
        self.assertTrue(
            mother_name_cell.startswith("'+"),
            f"Expected leading-quote-escaped formula, got: {mother_name_cell!r}",
        )
        self.assertTrue(
            nnc_no_cell.startswith("'-"),
            f"Expected leading-quote-escaped formula, got: {nnc_no_cell!r}",
        )
