"""
Security tests for reports app.

Covers: AC 1 (Fix #1 IDOR), AC 15/16 (Fix #14 report ownership).
"""
import uuid
from unittest.mock import patch

from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.test import Client, TestCase, override_settings
from django.urls import reverse
from django.utils import timezone

from institution.models import Institution
from patients.models import GMAssessment, Patient
from video.models import Video

User = get_user_model()

STATIC_OVERRIDE = override_settings(
    STORAGES={
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    },
    MULTI_INSTITUTION_ENABLED=True,
    RATELIMIT_ENABLE=False,
)


class ReportSecurityBase(TestCase):
    """Shared setup for report security tests."""

    def setUp(self):
        self.client = Client()
        self.inst_a = Institution.objects.create(name='Hospital A', slug='hosp-a')
        self.inst_b = Institution.objects.create(name='Hospital B', slug='hosp-b')

        self.superuser = User.objects.create_superuser(
            username='super', password='SuperPass123!', email='super@test.com',
            mobile_primary='0700000001',
        )
        self.staff_a = User.objects.create_user(
            username='staff_a', password='StaffPass123!', email='staff_a@test.com',
            is_staff=True, institution=self.inst_a, mobile_primary='0700000002',
        )
        self.staff_b = User.objects.create_user(
            username='staff_b', password='StaffPass123!', email='staff_b@test.com',
            is_staff=True, institution=self.inst_b, mobile_primary='0700000003',
        )

        # Patient at inst_b (belongs to the "wrong" institution for staff_a)
        self.patient_b = Patient.objects.create(
            bht='BHT-SEC-B-001',
            baby_name='Sec Baby B',
            mother_name='Sec Mother B',
            gender='Male',
            dob_tob=timezone.now() - timezone.timedelta(days=30),
            mo_delivery='Normal vaginal delivery (NVD)',
            pog_wks=38,
            pog_days=0,
            birth_weight=3000,
            ofc=34,
            tp_mobile='0771234567',
            institution=self.inst_b,
        )
        # Use bulk_create to bypass Video.save() which calls video_file.size on real storage
        self.video_b = Video.objects.bulk_create([Video(
            patient=self.patient_b,
            title='SecVideo',
            video_file='videos/dummy_b.mp4',
            recorded_on=timezone.now(),
        )])[0]
        self.assessment_b = GMAssessment.objects.create(
            patient=self.patient_b,
            video_file=self.video_b,
            date_of_assessment=timezone.now(),
        )


@STATIC_OVERRIDE
class IDORPDFDownloadTest(ReportSecurityBase):
    """AC 1: Cross-institution IDOR on GM assessment PDF → 404."""

    def test_cross_institution_gm_pdf_returns_404(self):
        """Staff from inst_a cannot download a GM assessment PDF for inst_b patient."""
        self.client.force_login(self.staff_a)
        url = reverse('reports:pdf-gm', kwargs={'assessment_id': self.assessment_b.id})
        response = self.client.get(url)
        self.assertEqual(response.status_code, 404)

    def test_superuser_can_access_any_institution_gm_pdf(self):
        """Superuser bypasses institution scope — assessment lookup succeeds (not 404)."""
        # Use raise_request_exception=False so a generator error returns 500, not a test failure
        client = Client(raise_request_exception=False)
        client.force_login(self.superuser)
        url = reverse('reports:pdf-gm', kwargs={'assessment_id': self.assessment_b.id})
        with patch('reports.views.GMAssessmentPDFGenerator') as mock_gen:
            mock_instance = mock_gen.return_value
            mock_instance.generate.side_effect = Exception('no pdf in test')
            response = client.get(url)
        # Superuser should reach PDF generation (not get 404 from institution scope)
        self.assertNotEqual(response.status_code, 404)


@STATIC_OVERRIDE
class ReportOwnershipTest(ReportSecurityBase):
    """AC 15/16: Report download ownership via session-keyed cache."""

    def _valid_file_id(self):
        return f"{uuid.uuid4()}.xlsx"

    def test_cross_session_download_denied(self):
        """AC 15: User B cannot download a report generated by User A."""
        self.client.force_login(self.staff_a)
        # Simulate staff_a generating a report by setting the cache key
        file_id = self._valid_file_id()
        session_key_a = self.client.session.session_key
        if not session_key_a:
            self.client.session.save()
            session_key_a = self.client.session.session_key
        cache.set(f"report_owner_{file_id}_{session_key_a}", self.staff_a.pk, 86400)

        # staff_b in a different session tries to download
        client_b = Client()
        client_b.force_login(self.staff_b)
        url = reverse('reports:download', kwargs={'file_id': file_id})
        response = client_b.get(url)
        self.assertEqual(response.status_code, 403)

    def test_own_report_download_passes_ownership_check(self):
        """AC 16: A user's own report passes the ownership check — response is not 403."""
        self.client.force_login(self.staff_a)
        session = self.client.session
        if not session.session_key:
            session.save()
        session_key = session.session_key

        file_id = self._valid_file_id()
        cache.set(f"report_owner_{file_id}_{session_key}", self.staff_a.pk, 86400)

        url = reverse('reports:download', kwargs={'file_id': file_id})
        response = self.client.get(url)
        # File doesn't exist on disk → 404, but ownership check passed (not 403)
        self.assertEqual(response.status_code, 404)
        self.assertNotEqual(response.status_code, 403)
