# Generated by Django 4.1.6 on 2025-11-09 08:39

from django.db import migrations


def populate_default_template(apps, schema_editor):
    """Create default report template and configuration"""
    ReportTemplate = apps.get_model('reports', 'ReportTemplate')
    ReportConfig = apps.get_model('reports', 'ReportConfig')

    # Create default report template
    ReportTemplate.objects.create(
        name="Default Medical Report",
        description="Standard template for neurodevelopmental assessment reports",
        header_text="<h2>Neurodevelopmental Assessment System (NDAS)</h2><p>Confidential Medical Report</p>",
        footer_text="<p><small>This is a confidential medical record. Unauthorized disclosure is prohibited.</small></p>",
        is_active=True,
        is_default=True
    )

    # Create default configurations
    configs = [
        {
            'key': 'temp_file_retention_hours',
            'value': '24',
            'value_type': 'INTEGER',
            'description': 'Number of hours to retain temporary report files before cleanup'
        },
        {
            'key': 'max_async_wait_minutes',
            'value': '5',
            'value_type': 'INTEGER',
            'description': 'Maximum minutes to wait for async report generation before timeout'
        },
        {
            'key': 'pdf_page_size',
            'value': 'A4',
            'value_type': 'STRING',
            'description': 'Default page size for PDF reports (A4 or LETTER)'
        },
        {
            'key': 'async_threshold_records',
            'value': '100',
            'value_type': 'INTEGER',
            'description': 'Number of records above which report generation becomes asynchronous'
        }
    ]

    for config_data in configs:
        ReportConfig.objects.create(**config_data)


def reverse_populate(apps, schema_editor):
    """Remove default data on migration rollback"""
    ReportTemplate = apps.get_model('reports', 'ReportTemplate')
    ReportConfig = apps.get_model('reports', 'ReportConfig')

    ReportTemplate.objects.filter(name="Default Medical Report").delete()
    ReportConfig.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_default_template, reverse_populate),
    ]
