# Generated by Django 4.2.7 on 2025-12-17 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_alter_bookmark_bookmark_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(db_index=True, help_text='Short clinical name (e.g., Bronchial Asthma)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed clinical description')),
                ('date_of_onset', models.DateField(blank=True, help_text='Date when problem first started', null=True)),
                ('date_identified', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date problem was first documented')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('chronic', 'Chronic'), ('inactive', 'Inactive')], db_index=True, default='active', help_text='Current status of the problem', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], help_text='Severity level of the problem', max_length=20, null=True)),
                ('date_resolved', models.DateField(blank=True, help_text='Date when problem was resolved (auto-populated when status changes to resolved)', null=True)),
                ('action_taken', models.TextField(blank=True, help_text='Summary of treatments, investigations, and referrals')),
                ('outcome', models.TextField(blank=True, help_text='Response to treatment / current outcome')),
                ('comments', models.TextField(blank=True, help_text='Additional clinical notes (optional)')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_added', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('last_edit_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By')),
                ('patient', models.ForeignKey(help_text='Patient associated with this problem', on_delete=django.db.models.deletion.CASCADE, related_name='problem_list', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Problem',
                'verbose_name_plural': 'Patient Problems',
                'ordering': ['-date_identified'],
            },
        ),
        migrations.CreateModel(
            name='ProblemAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(help_text='Description of action taken')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this action was performed')),
                ('performed_by', models.ForeignKey(help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(help_text='Problem this action relates to', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='problemlist.problem')),
            ],
            options={
                'verbose_name': 'Problem Action',
                'verbose_name_plural': 'Problem Actions',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['patient', 'status'], name='problemlist_patient_0f4ec0_idx'),
        ),
    ]
