# Generated by Django 6.0 on 2026-02-24 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="institution_logos/"
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("GRACE", "Grace Period"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("subscription_start", models.DateField(blank=True, null=True)),
                ("grace_period_end", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="SUPERADMIN who onboarded this institution",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institutions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edit_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_edited",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Edited By",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
