# Generated by Django 6.0 on 2026-09-17 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "institution",
            "0007_institutionswitchlog_add_timestamped_mixin",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("backup", "Backup"),
                            ("restore", "Restore"),
                            ("pre_restore_snapshot", "Pre-Restore Snapshot"),
                        ],
                        db_index=True,
                        default="backup",
                        help_text="Kind of job this record tracks.",
                        max_length=25,
                        verbose_name="Job Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current lifecycle state of the job.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "progress_pct",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Approximate completion percentage (0-100).",
                        verbose_name="Progress %",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Populated when status=failed.",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "last_edit_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_edited",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Edited By",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        help_text="Institution this job is scoped to. Null = system-wide (Epic 1.2).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_jobs",
                        to="institution.institution",
                        verbose_name="Scope",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered this job (set explicitly, not via middleware).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_jobs_triggered",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Triggered By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Job",
                "verbose_name_plural": "Backup Jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scope", "status"], name="backup_scope_status_idx"
                    )
                ],
            },
        ),
    ]
