# Generated by Django 6.0 on 2026-09-18 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backup", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupjob",
            name="progress_pct",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Approximate completion percentage (0-100).",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Progress %",
            ),
        ),
    ]
