# Generated by Django 6.0 on 2026-09-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backup", "0002_alter_backupjob_progress_pct"),
        ("institution", "0007_institutionswitchlog_add_timestamped_mixin"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupjob",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("single", "Single Institution"),
                    ("multi", "Multiple Institutions"),
                    ("system", "System-Wide"),
                ],
                db_index=True,
                default="single",
                help_text="Story 1.2: whether this job covers a single institution (`scope`), an explicit multi-institution subset (`scopes`), or the whole system (both empty).",
                max_length=10,
                verbose_name="Scope Type",
            ),
        ),
        migrations.AddField(
            model_name="backupjob",
            name="scopes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Explicit institution subset for scope_type=multi. Unused (empty) for single/system jobs.",
                related_name="backup_jobs_multi",
                to="institution.institution",
                verbose_name="Scopes",
            ),
        ),
    ]
