# Generated by Django 6.0 on 2026-09-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backup", "0003_backupjob_scope_type_backupjob_scopes"),
        ("institution", "0007_institutionswitchlog_add_timestamped_mixin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupjob",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                help_text="Single institution this job is scoped to when scope_type=single. Null when scope_type=multi (see `scopes` instead) or scope_type=system (unfiltered, system-wide).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backup_jobs",
                to="institution.institution",
                verbose_name="Scope",
            ),
        ),
    ]
