# Generated by Django 6.0 on 2026-09-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backup", "0005_backupjob_archive_checksum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupjob",
            name="archive_checksum",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Story 1.3: whole-archive SHA-256, computed by hashing the finished .zip file on disk after it is closed. Empty until the job completes.",
                max_length=64,
                verbose_name="Archive Checksum",
            ),
        ),
    ]
