# Generated by Django 6.0 on 2026-09-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backup", "0007_backupjob_date_filter_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupjob",
            name="date_filter_end",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Story 1.4: optional inclusive upper bound (on Patient.created_at's date) this job's export was narrowed to. Null when no date filter was applied.",
                null=True,
                verbose_name="Date Filter End",
            ),
        ),
        migrations.AlterField(
            model_name="backupjob",
            name="date_filter_start",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Story 1.4: optional inclusive lower bound (on Patient.created_at's date) this job's export was narrowed to. Null when no date filter was applied -- including every Story 1.1-1.3 job, which predates this field and is never backfilled.",
                null=True,
                verbose_name="Date Filter Start",
            ),
        ),
    ]
