# Generated by Django 6.0 on 2026-09-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backup", "0008_alter_backupjob_date_filter_end_and_more"),
        ("institution", "0007_institutionswitchlog_add_timestamped_mixin"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupjob",
            name="trigger_institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Story 1.5: the institution context the job was triggered from. Used as the delivery institution for the completion notification (a super admin's multi/system job has scope=null). Null on jobs that predate this field, which are never backfilled.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backup_jobs_triggered_from",
                to="institution.institution",
                verbose_name="Trigger Institution",
            ),
        ),
    ]
