# Generated by Django 6.0 on 2026-09-20 12:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0009_backupjob_trigger_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Original Filename')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Size (bytes)')),
                ('archive_sha256', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of the uploaded file, computed while it was streamed to disk.', max_length=64, verbose_name='Archive SHA-256')),
                ('allow_unverified', models.BooleanField(default=False, help_text='Accept an archive whose originating backup job is unknown on this system.', verbose_name='Allow Unverified Origin')),
                ('status', models.CharField(choices=[('validating', 'Validating'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='validating', max_length=10, verbose_name='Status')),
                ('progress_pct', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Progress %')),
                ('error_code', models.CharField(blank=True, choices=[('not_a_zip', 'Not a valid zip archive'), ('encrypted_member', 'Archive contains an encrypted member'), ('duplicate_member', 'Archive contains duplicate member names'), ('unexpected_member', 'Archive contains an unexpected member'), ('unsafe_member_path', 'Archive contains an unsafe member path'), ('symlink_member', 'Archive contains a symlink'), ('excessive_expansion', 'Archive expands implausibly'), ('manifest_missing', 'manifest.json is missing'), ('manifest_invalid', 'manifest.json is invalid'), ('manifest_unsupported', 'Unsupported manifest version or algorithm'), ('db_export_missing', 'db_export.json is missing'), ('schema_mismatch', 'Schema version mismatch'), ('archive_checksum_mismatch', 'Archive checksum mismatch'), ('origin_not_verifiable', 'Origin cannot be verified'), ('file_missing', 'A listed file is missing from the archive'), ('file_not_listed', 'An archive file is not listed in the manifest'), ('file_checksum_mismatch', 'File checksum mismatch')], default='', max_length=40, verbose_name='Error Code')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('authenticity', models.CharField(blank=True, choices=[('verified', 'Verified'), ('unverified', 'Unverified origin')], default='', max_length=10, verbose_name='Authenticity')),
                ('source_job_id', models.PositiveIntegerField(blank=True, help_text="`source_job_id` from the archive's manifest.", null=True, verbose_name='Source Job ID')),
                ('manifest_summary', models.JSONField(blank=True, help_text="Summary of the validated archive's manifest; set only when status=validated.", null=True, verbose_name='Manifest Summary')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_added', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('last_edit_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Restore Upload',
                'verbose_name_plural': 'Restore Uploads',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'validating')), fields=('uploaded_by',), name='restore_one_validating_per_user')],
            },
        ),
    ]
