# Generated by Django 6.0 on 2026-09-20 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0010_restoreupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restoreupload',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At'),
        ),
        migrations.AddField(
            model_name='restoreupload',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_uploads_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By'),
        ),
        migrations.AddField(
            model_name='restoreupload',
            name='confirmed_snapshot',
            field=models.JSONField(blank=True, help_text='Story 2.2: the exact facts previewed at confirmation (plus live counts and the preview digest); the hand-off contract for the restore-apply stories.', null=True, verbose_name='Confirmed Snapshot'),
        ),
        migrations.AlterField(
            model_name='restoreupload',
            name='status',
            field=models.CharField(choices=[('validating', 'Validating'), ('validated', 'Validated'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='validating', max_length=10, verbose_name='Status'),
        ),
    ]
