# Generated by Django 6.0 on 2026-09-21 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0011_restoreupload_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restoreupload',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'confirmed'), _negated=True), models.Q(('confirmed_at__isnull', False), ('confirmed_snapshot__isnull', False)), _connector='OR'), name='restore_confirmed_has_snapshot'),
        ),
    ]
