# Generated by Django 6.0 on 2026-09-21 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0012_restoreupload_restore_confirmed_has_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='pre_restore_snapshot',
            field=models.ForeignKey(blank=True, help_text='Story 2.3: the snapshot job a restore took of the current data before changing it. Null for every other job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores_using_snapshot', to='backup.backupjob', verbose_name='Pre-Restore Snapshot'),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='restore_upload',
            field=models.ForeignKey(blank=True, help_text='Story 2.3: the confirmed archive a restore job applies. Null for every other job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_jobs', to='backup.restoreupload', verbose_name='Restore Upload'),
        ),
        migrations.AlterField(
            model_name='restoreupload',
            name='status',
            field=models.CharField(choices=[('validating', 'Validating'), ('validated', 'Validated'), ('confirmed', 'Confirmed'), ('applying', 'Applying'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='validating', max_length=10, verbose_name='Status'),
        ),
    ]
