# Generated by Django 6.0 on 2026-09-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backup", "0013_backupjob_pre_restore_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restoreupload",
            name="match_summary",
            field=models.JSONField(
                blank=True,
                help_text="Story 2.4: the final skip/import/excluded partition, computed once, for a single-institution date-scoped archive. Set only alongside manifest_summary, in the same terminal save, when status=validated. Null for a full-scope archive and for a multi- or system-scoped date-scoped archive (no per-record institution can be resolved for those yet).",
                null=True,
                verbose_name="Match Summary",
            ),
        ),
    ]
