# Generated by Django 6.0 on 2026-09-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0015_backupjob_restore_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='restore_audit',
            field=models.JSONField(blank=True, help_text="Story 2.6: the self-contained, PHI-free audit record of a finished restore job (actor, archive, scope, outcome, timestamps, counts, snapshot). Written in the job's terminal save, for completed and failed restores alike. Null for every other job and for a restore that never finished.", null=True, verbose_name='Restore Audit'),
        ),
    ]
