# Generated by Django 4.1.6 on 2025-08-24 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient associated with this video",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="indecation_for_gma",
            field=models.ManyToManyField(
                blank=True,
                help_text="Medical indications for General Movement Assessment",
                to="patients.indicationsforgma",
                verbose_name="Indications for GMA",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="indicationsforgma",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="indicationsforgma",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="hineassessment",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="hineassessment",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="hineassessment",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient being assessed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hine_assessments",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="help",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="help",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="gmassessment",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="gmassessment",
            name="diagnosis",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selected diagnoses for this assessment",
                to="patients.diagnosislist",
                verbose_name="Diagnosis",
            ),
        ),
        migrations.AddField(
            model_name="gmassessment",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="gmassessment",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient this assessment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="gmassessment",
            name="video_file",
            field=models.OneToOneField(
                help_text="Associated video file for this assessment",
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.video",
                verbose_name="Video File",
            ),
        ),
        migrations.AddField(
            model_name="diagnosislist",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="diagnosislist",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="developmentalassessment",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="developmentalassessment",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="developmentalassessment",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient being assessed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="developmental_assessments",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="cdicrecord",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="cdicrecord",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="cdicrecord",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient this CDIC record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this bookmark",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_added",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added By",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="last_edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_edited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Edited By",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient this attachment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["patient", "-created_at"], name="patients_vi_patient_c19bed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["processing_status"], name="patients_vi_process_2b37a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["added_by", "-created_at"],
                name="patients_vi_added_b_543ac4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["recorded_on"], name="patients_vi_recorde_27cabb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["is_public", "access_level"],
                name="patients_vi_is_publ_47b9b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["baby_name", "mother_name"], name="patient_names_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["dob_tob", "gender"], name="patient_birth_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["created_at", "moh_area"], name="patient_location_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["resuscitated", "birth_weight"], name="patient_risk_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hineassessment",
            index=models.Index(
                fields=["patient", "-date_of_assessment"],
                name="patients_hi_patient_7c5aec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hineassessment",
            index=models.Index(
                fields=["score", "date_of_assessment"],
                name="patients_hi_score_8d7762_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hineassessment",
            index=models.Index(
                fields=["assessment_done_by"], name="patients_hi_assessm_7e096e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="help",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="patients_he_is_acti_7996d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="help",
            index=models.Index(fields=["title"], name="patients_he_title_9ac476_idx"),
        ),
        migrations.AddIndex(
            model_name="gmassessment",
            index=models.Index(
                fields=["patient", "date_of_assessment"], name="gma_patient_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gmassessment",
            index=models.Index(
                fields=["diagnosis_conclusion", "date_of_assessment"],
                name="gma_conclusion_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gmassessment",
            index=models.Index(
                fields=["next_assessment_date", "parent_informed"],
                name="gma_followup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="developmentalassessment",
            index=models.Index(
                fields=["patient", "-date_of_assessment"],
                name="patients_de_patient_c69fff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="developmentalassessment",
            index=models.Index(
                fields=["is_dx_normal", "date_of_assessment"],
                name="patients_de_isDxNor_948d70_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="developmentalassessment",
            index=models.Index(
                fields=["assessment_done_by"], name="patients_de_assessm_db9492_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cdicrecord",
            index=models.Index(
                fields=["patient", "assessment_date"], name="cdic_patient_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cdicrecord",
            index=models.Index(
                fields=["is_discharged", "assessment_date"], name="cdic_discharge_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cdicrecord",
            index=models.Index(
                fields=["next_appointment_date", "is_discharged"],
                name="cdic_followup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cdicrecord",
            index=models.Index(
                fields=["assessment_done_by", "assessment_date"],
                name="cdic_assessor_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["owner", "-created_at"], name="bookmark_owner_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["bookmark_type", "object_id"], name="bookmark_type_object_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["is_public", "priority"], name="bookmark_public_priority_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["title", "bookmark_type"], name="bookmark_title_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["patient", "-created_at"], name="attachment_patient_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["attachment_type", "-created_at"],
                name="attachment_type_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["added_by", "-created_at"], name="attachment_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["is_sensitive", "access_level"], name="attachment_access_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["scan_result", "is_scanned"], name="attachment_security_idx"
            ),
        ),
    ]
