# Generated by Django 4.1.6 on 2023-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdicrecord",
            name="next_appoinment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
