# Generated by Django 4.2.16 on 2025-08-24 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_gmassessment_gma_valid_assessment_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gmassessment',
            name='gma_valid_assessment_date',
        ),
    ]
