# Generated by Django 4.1.6 on 2025-08-27 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="added_by",
        ),
        migrations.RemoveField(
            model_name="video",
            name="last_edit_by",
        ),
        migrations.RemoveField(
            model_name="video",
            name="patient",
        ),
    ]
