# Generated by Django 4.1.6 on 2023-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_alter_cdicrecord_next_appoinment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdicrecord",
            name="dischaged_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
