# Generated by Django 4.1.6 on 2025-08-27 03:38
# Modified to fix migration issue with indexes on removed fields

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_initial"),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle model move properly
        # The Video model is being moved to the video app, so we only need
        # to update the state (not the database) since the fields will be
        # removed when the model is deleted in the next migration
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="video",
                    name="added_by",
                ),
                migrations.RemoveField(
                    model_name="video",
                    name="last_edit_by",
                ),
                migrations.RemoveField(
                    model_name="video",
                    name="patient",
                ),
            ],
            # No database operations needed - fields will be removed when table is deleted
            database_operations=[],
        ),
    ]
