# Generated by Django 4.1.6 on 2025-08-27 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_remove_video_added_by_remove_video_last_edit_by_and_more"),
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmassessment",
            name="video_file",
            field=models.OneToOneField(
                help_text="Associated video file for this assessment",
                on_delete=django.db.models.deletion.CASCADE,
                to="video.video",
                verbose_name="Video File",
            ),
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
