# Generated by Django 4.2.16 on 2025-08-24 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_dynamic_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gmassessment',
            constraint=models.CheckConstraint(check=models.Q(('date_of_assessment__lte', datetime.datetime(2025, 8, 24, 16, 42, 15, 460825, tzinfo=datetime.timezone.utc))), name='gma_valid_assessment_date'),
        ),
    ]
