# Generated by Django 4.1.6 on 2023-05-17 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_alter_cdicrecord_dischaged_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cdicrecord",
            name="is_assessment_completed",
        ),
        migrations.RemoveField(
            model_name="gmassessment",
            name="is_assessment_completed",
        ),
    ]
