# Generated by Django 4.1.6 on 2025-08-23 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_remove_gmassessment_gma_valid_assessment_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gmassessment",
            name="gma_valid_assessment_date",
        ),
        migrations.AddConstraint(
            model_name="gmassessment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "date_of_assessment__lte",
                        datetime.datetime(
                            2025, 8, 23, 7, 47, 33, 351985, tzinfo=datetime.timezone.utc
                        ),
                    )
                ),
                name="gma_valid_assessment_date",
            ),
        ),
    ]
