# Generated by Django 4.2.16 on 2025-08-24 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_gmassessment_gma_valid_assessment_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cdicrecord',
            name='cdic_valid_assessment_date',
        ),
        migrations.RemoveConstraint(
            model_name='gmassessment',
            name='gma_valid_assessment_date',
        ),
    ]
