# Generated by Django 4.1.6 on 2023-05-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_remove_cdicrecord_is_assessment_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentalassessment",
            name="isDxNormal",
            field=models.BooleanField(default=False),
        ),
    ]
