# Generated by Django 4.1.6 on 2025-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_gmassessment_video_file_delete_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="indecation_for_gma_other",
            field=models.TextField(
                blank=True,
                help_text="Specify other indication details when 'Other' is selected",
                null=True,
                verbose_name="Other GMA Indication Details",
            ),
        ),
    ]
