# Generated by Django 4.1.6 on 2023-05-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_developmentalassessment_isdxnormal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="dob_tob",
            field=models.DateField(),
        ),
    ]
