# Generated by Django 4.1.6 on 2025-11-05 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0005_patient_indecation_for_gma_other"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="bookmark_type",
            field=models.CharField(
                choices=[
                    ("Patient", "Patient"),
                    ("Video", "Video"),
                    ("GMA", "GMA"),
                    ("HINE", "HINE"),
                    ("Attachment", "Attachment"),
                    ("DA", "DA"),
                    ("CDICR", "CDICR"),
                    ("GPA", "GPA"),
                ],
                db_index=True,
                default="Video",
                help_text="Type of content being bookmarked",
                max_length=20,
                verbose_name="Bookmark Type",
            ),
        ),
        migrations.AlterField(
            model_name="cdicrecord",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient this CDIC record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cdic_records",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="gmassessment",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient this assessment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gm_assessments",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.CreateModel(
            name="GeneralPaediatricAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "assessment_date",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Date and time when the assessment was performed",
                        verbose_name="Assessment Date",
                    ),
                ),
                (
                    "healthcare_provider",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the healthcare professional who performed the assessment",
                        max_length=200,
                        verbose_name="Healthcare Provider",
                    ),
                ),
                (
                    "current_problems",
                    models.TextField(
                        help_text="Current medical problems and presenting complaints",
                        verbose_name="Current Problems",
                    ),
                ),
                (
                    "physical_examination",
                    models.TextField(
                        help_text="Detailed physical examination findings",
                        verbose_name="Physical Examination",
                    ),
                ),
                (
                    "investigation_summary",
                    models.TextField(
                        help_text="Summary of investigations performed and results",
                        verbose_name="Investigation Summary",
                    ),
                ),
                (
                    "prescribed_medications",
                    models.TextField(
                        help_text="Current medications and treatment prescriptions",
                        verbose_name="Prescribed Medications",
                    ),
                ),
                (
                    "next_plan",
                    models.TextField(
                        help_text="Planned next steps, goals, and interventions",
                        verbose_name="Next Plan/Goals",
                    ),
                ),
                (
                    "next_assessment_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Scheduled date for next assessment (optional)",
                        null=True,
                        verbose_name="Next Assessment Date",
                    ),
                ),
                (
                    "is_discharged",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the patient has been discharged from paediatric care",
                        verbose_name="Is Discharged",
                    ),
                ),
                (
                    "discharge_plan",
                    models.TextField(
                        blank=True,
                        help_text="Discharge planning and follow-up instructions",
                        null=True,
                        verbose_name="Discharge Plan",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "discharged_authorized_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who authorized the discharge",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_gpa_discharges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Discharged Authorized By",
                    ),
                ),
                (
                    "last_edit_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_edited",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Edited By",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient this GPA record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gpa_assessments",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "General Paediatric Assessment",
                "verbose_name_plural": "General Paediatric Assessments",
                "ordering": ["-assessment_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="generalpaediatricassessment",
            index=models.Index(
                fields=["patient", "assessment_date"], name="gpa_patient_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generalpaediatricassessment",
            index=models.Index(
                fields=["is_discharged", "assessment_date"], name="gpa_discharge_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generalpaediatricassessment",
            index=models.Index(
                fields=["next_assessment_date", "is_discharged"],
                name="gpa_followup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generalpaediatricassessment",
            index=models.Index(
                fields=["healthcare_provider", "assessment_date"],
                name="gpa_provider_idx",
            ),
        ),
    ]
