# Generated by Django 6.0 on 2025-12-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_alter_bookmark_bookmark_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosislist",
            name="abr",
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name="diagnosislist",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="help",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Title of the help content",
                max_length=200,
                unique=True,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="indicationsforgma",
            name="level",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                db_index=True,
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="indicationsforgma",
            name="title",
            field=models.CharField(db_index=True, max_length=75, unique=True),
        ),
    ]
