# Generated by Django 4.2.16 on 2025-08-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_gmassessment_gma_valid_assessment_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gmassessment',
            name='gma_valid_assessment_date',
        ),
    ]
