# Generated by Django 6.0 on 2026-02-24 17:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0001_initial"),
        ("patients", "0007_alter_diagnosislist_abr_alter_diagnosislist_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnosislist",
            options={
                "ordering": ["title"],
                "verbose_name": "Diagnosis",
                "verbose_name_plural": "Diagnoses",
            },
        ),
        migrations.AlterModelOptions(
            name="indicationsforgma",
            options={
                "ordering": ["level", "title"],
                "verbose_name": "Indication for GMA",
                "verbose_name_plural": "Indications for GMA",
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Institution this patient belongs to. Set by Story 1.6 data migration for existing patients.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patients",
                to="institution.institution",
                verbose_name="Institution",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Descriptive title for the attachment (max 200 characters)",
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Title can only contain letters, numbers, spaces, and basic punctuation (-, _, ., comma, parentheses, !, ?).",
                        regex="^[a-zA-Z0-9\\s\\-_\\.(),!?]+$",
                    )
                ],
                verbose_name="Title",
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosislist",
            index=models.Index(fields=["title"], name="patients_di_title_033f4d_idx"),
        ),
        migrations.AddIndex(
            model_name="diagnosislist",
            index=models.Index(fields=["abr"], name="patients_di_abr_bcb09e_idx"),
        ),
        migrations.AddIndex(
            model_name="indicationsforgma",
            index=models.Index(fields=["title"], name="patients_in_title_ff33a8_idx"),
        ),
        migrations.AddIndex(
            model_name="indicationsforgma",
            index=models.Index(fields=["level"], name="patients_in_level_f4a442_idx"),
        ),
    ]
