# Generated by Django 4.1.6 on 2023-05-20 17:18

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0007_alter_patient_dob_tob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="help",
            name="description",
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
