# Generated by Django 4.2.16 on 2025-08-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_gmassessment_gma_valid_assessment_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attachment',
            name='attachment_positive_file_size',
        ),
        migrations.RemoveConstraint(
            model_name='attachment',
            name='attachment_title_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique_bookmark_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='bookmark_title_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='bookmark_valid_object_id',
        ),
        migrations.RemoveConstraint(
            model_name='cdicrecord',
            name='cdic_valid_next_appointment_date',
        ),
        migrations.RemoveConstraint(
            model_name='cdicrecord',
            name='cdic_valid_discharge_date',
        ),
        migrations.RemoveConstraint(
            model_name='cdicrecord',
            name='cdic_discharge_completeness',
        ),
        migrations.RemoveConstraint(
            model_name='developmentalassessment',
            name='unique_dev_assessment_per_patient_date',
        ),
        migrations.RemoveConstraint(
            model_name='gmassessment',
            name='gma_valid_next_assessment_date',
        ),
        migrations.RemoveConstraint(
            model_name='hineassessment',
            name='unique_hine_assessment_per_patient_date',
        ),
        migrations.RemoveConstraint(
            model_name='patient',
            name='valid_birth_weight',
        ),
        migrations.RemoveConstraint(
            model_name='patient',
            name='valid_pog_weeks',
        ),
        migrations.RemoveConstraint(
            model_name='patient',
            name='valid_pog_days',
        ),
        migrations.RemoveConstraint(
            model_name='video',
            name='positive_file_size',
        ),
        migrations.RemoveConstraint(
            model_name='video',
            name='positive_compressed_file_size',
        ),
    ]
