# Generated by Django 6.0 on 2026-02-24 18:10

import ndas.custom_codes.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0008_alter_diagnosislist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="attachment",
            field=models.FileField(
                help_text="Upload file (Images: 10MB max, Videos: 2GB max, Others: 100MB max)",
                upload_to=ndas.custom_codes.validators.get_institution_attachment_path,
                validators=[ndas.custom_codes.validators.validate_attachment_file],
                verbose_name="Attachment File",
            ),
        ),
    ]
