# Generated by Django 4.2.16 on 2025-08-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_help_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mo_delivery',
            field=models.CharField(choices=[('Normal vaginal delivery (NVD)', 'Normal vaginal delivery (NVD)'), ('Assisted vaginal delivery (AVD)', 'Assisted vaginal delivery (AVD)'), ('Forcep delivery', 'Forcep delivery'), ('Vacume delivery', 'Vacume delivery'), ('Emergency LSCS', 'Emergency LSCS'), ('Elective LSCS', 'Elective LSCS'), ('VBAC', 'Vaginal birth after CS (VBAC)'), ('Home delivery', 'Home delivery'), ('Other', 'Other')], default='NVD', max_length=35),
        ),
    ]
