# Generated by Django 6.0 on 2026-02-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0003_patientmovelog"),
        ("patients", "0009_alter_attachment_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Institution this patient belongs to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patients",
                to="institution.institution",
                verbose_name="Institution",
            ),
        ),
    ]
