# Generated by Django 4.2.16 on 2025-08-21 16:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0010_alter_patient_options_remove_patient_added_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdicrecord',
            options={'ordering': ['-assessment_date', '-created_at'], 'verbose_name': 'CDIC Record', 'verbose_name_plural': 'CDIC Records'},
        ),
        migrations.AlterModelOptions(
            name='gmassessment',
            options={'ordering': ['-date_of_assessment', '-created_at'], 'verbose_name': 'GM Assessment', 'verbose_name_plural': 'GM Assessments'},
        ),
        migrations.RemoveField(
            model_name='cdicrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cdicrecord',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='cdicrecord',
            name='dischaged_date',
        ),
        migrations.RemoveField(
            model_name='cdicrecord',
            name='dishcharged_by',
        ),
        migrations.RemoveField(
            model_name='cdicrecord',
            name='edit_by',
        ),
        migrations.RemoveField(
            model_name='cdicrecord',
            name='edit_on',
        ),
        migrations.RemoveField(
            model_name='cdicrecord',
            name='next_appoinment_date',
        ),
        migrations.RemoveField(
            model_name='cdicrecord',
            name='next_appoinment_plan',
        ),
        migrations.RemoveField(
            model_name='gmassessment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gmassessment',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='gmassessment',
            name='diagnosis_conclution',
        ),
        migrations.RemoveField(
            model_name='gmassessment',
            name='edit_by',
        ),
        migrations.RemoveField(
            model_name='gmassessment',
            name='edit_on',
        ),
        migrations.RemoveField(
            model_name='gmassessment',
            name='managment_plan',
        ),
        migrations.RemoveField(
            model_name='gmassessment',
            name='parant_informed',
        ),
        migrations.AddField(
            model_name='cdicrecord',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_added', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='cdicrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this record was created', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cdicrecord',
            name='discharge_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date when the patient was discharged from CDIC care', null=True, verbose_name='Discharge Date'),
        ),
        migrations.AddField(
            model_name='cdicrecord',
            name='discharged_by',
            field=models.CharField(blank=True, db_index=True, help_text='Name or ID of the healthcare professional who authorized discharge', max_length=200, null=True, verbose_name='Discharged By'),
        ),
        migrations.AddField(
            model_name='cdicrecord',
            name='last_edit_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AddField(
            model_name='cdicrecord',
            name='next_appointment_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Scheduled date and time for next appointment', null=True, verbose_name='Next Appointment Date'),
        ),
        migrations.AddField(
            model_name='cdicrecord',
            name='next_appointment_plan',
            field=models.TextField(blank=True, help_text='Planned activities and goals for next appointment', null=True, verbose_name='Next Appointment Plan'),
        ),
        migrations.AddField(
            model_name='cdicrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='gmassessment',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_added', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='gmassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this record was created', verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmassessment',
            name='diagnosis_conclusion',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('ABNORMAL', 'ABNORMAL')], db_index=True, default='NORMAL', help_text='Overall assessment conclusion', max_length=8, verbose_name='Diagnosis Conclusion'),
        ),
        migrations.AddField(
            model_name='gmassessment',
            name='last_edit_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AddField(
            model_name='gmassessment',
            name='management_plan',
            field=models.TextField(blank=True, help_text='Recommended treatment and intervention plan', null=True, verbose_name='Management Plan'),
        ),
        migrations.AddField(
            model_name='gmassessment',
            name='parent_informed',
            field=models.BooleanField(default=False, help_text='Whether the parent has been informed of the results', verbose_name='Parent Informed'),
        ),
        migrations.AddField(
            model_name='gmassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='cdicrecord',
            name='assessment',
            field=models.TextField(blank=True, help_text='Detailed assessment findings and observations', null=True, verbose_name='Assessment Details'),
        ),
        migrations.AlterField(
            model_name='cdicrecord',
            name='assessment_date',
            field=models.DateField(db_index=True, help_text='Date when the assessment was performed', verbose_name='Assessment Date'),
        ),
        migrations.AlterField(
            model_name='cdicrecord',
            name='assessment_done_by',
            field=models.CharField(blank=True, db_index=True, help_text='Name or ID of the healthcare professional who performed the assessment', max_length=200, null=True, verbose_name='Assessment Done By'),
        ),
        migrations.AlterField(
            model_name='cdicrecord',
            name='discharge_plan',
            field=models.TextField(blank=True, help_text='Discharge planning and follow-up instructions', null=True, verbose_name='Discharge Plan'),
        ),
        migrations.AlterField(
            model_name='cdicrecord',
            name='is_discharged',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the patient has been discharged from CDIC care', verbose_name='Is Discharged'),
        ),
        migrations.AlterField(
            model_name='cdicrecord',
            name='patient',
            field=models.ForeignKey(help_text='Patient this CDIC record belongs to', on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='cdicrecord',
            name='today_interventions',
            field=models.TextField(blank=True, help_text='Interventions and treatments provided during this visit', null=True, verbose_name="Today's Interventions"),
        ),
        migrations.AlterField(
            model_name='gmassessment',
            name='date_of_assessment',
            field=models.DateTimeField(db_index=True, help_text='When this assessment was performed', verbose_name='Date of Assessment'),
        ),
        migrations.AlterField(
            model_name='gmassessment',
            name='diagnosis',
            field=models.ManyToManyField(blank=True, help_text='Selected diagnoses for this assessment', to='patients.diagnosislist', verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='gmassessment',
            name='diagnosis_other',
            field=models.TextField(blank=True, help_text='Additional diagnosis notes not covered by standard list', null=True, verbose_name='Other Diagnosis'),
        ),
        migrations.AlterField(
            model_name='gmassessment',
            name='next_assessment_date',
            field=models.DateField(blank=True, db_index=True, help_text='Scheduled date for follow-up assessment', null=True, verbose_name='Next Assessment Date'),
        ),
        migrations.AlterField(
            model_name='gmassessment',
            name='patient',
            field=models.ForeignKey(help_text='Patient this assessment belongs to', on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='gmassessment',
            name='video_file',
            field=models.OneToOneField(help_text='Associated video file for this assessment', on_delete=django.db.models.deletion.CASCADE, to='patients.video', verbose_name='Video File'),
        ),
        migrations.AddIndex(
            model_name='cdicrecord',
            index=models.Index(fields=['patient', 'assessment_date'], name='cdic_patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cdicrecord',
            index=models.Index(fields=['is_discharged', 'assessment_date'], name='cdic_discharge_idx'),
        ),
        migrations.AddIndex(
            model_name='cdicrecord',
            index=models.Index(fields=['next_appointment_date', 'is_discharged'], name='cdic_followup_idx'),
        ),
        migrations.AddIndex(
            model_name='cdicrecord',
            index=models.Index(fields=['assessment_done_by', 'assessment_date'], name='cdic_assessor_idx'),
        ),
        migrations.AddIndex(
            model_name='gmassessment',
            index=models.Index(fields=['patient', 'date_of_assessment'], name='gma_patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='gmassessment',
            index=models.Index(fields=['diagnosis_conclusion', 'date_of_assessment'], name='gma_conclusion_date_idx'),
        ),
        migrations.AddIndex(
            model_name='gmassessment',
            index=models.Index(fields=['next_assessment_date', 'parent_informed'], name='gma_followup_idx'),
        ),
        migrations.AddConstraint(
            model_name='cdicrecord',
            constraint=models.CheckConstraint(check=models.Q(('assessment_date__lte', datetime.date(2025, 8, 21))), name='cdic_valid_assessment_date'),
        ),
        migrations.AddConstraint(
            model_name='cdicrecord',
            constraint=models.CheckConstraint(check=models.Q(('next_appointment_date__gte', models.F('assessment_date')), ('next_appointment_date__isnull', True), _connector='OR'), name='cdic_valid_next_appointment_date'),
        ),
        migrations.AddConstraint(
            model_name='cdicrecord',
            constraint=models.CheckConstraint(check=models.Q(('discharge_date__gte', models.F('assessment_date')), ('discharge_date__isnull', True), _connector='OR'), name='cdic_valid_discharge_date'),
        ),
        migrations.AddConstraint(
            model_name='cdicrecord',
            constraint=models.CheckConstraint(check=models.Q(('is_discharged', False), models.Q(('is_discharged', True), ('discharge_date__isnull', False), ('discharged_by__isnull', False)), _connector='OR'), name='cdic_discharge_completeness'),
        ),
        migrations.AddConstraint(
            model_name='gmassessment',
            constraint=models.CheckConstraint(check=models.Q(('date_of_assessment__lte', datetime.datetime(2025, 8, 21, 16, 25, 27, 813482, tzinfo=datetime.timezone.utc))), name='gma_valid_assessment_date'),
        ),
        migrations.AddConstraint(
            model_name='gmassessment',
            constraint=models.CheckConstraint(check=models.Q(('next_assessment_date__gte', models.F('date_of_assessment__date'))), name='gma_valid_next_assessment_date'),
        ),
    ]
