# Generated by Django 4.1.6 on 2025-08-27 03:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ndas.custom_codes.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0003_remove_video_added_by_remove_video_last_edit_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        db_index=True,
                        help_text="Upload the video file here",
                        upload_to="videos/%Y/",
                        validators=[ndas.custom_codes.validators.validate_video_file],
                        verbose_name="Video File",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Descriptive title for the video (max 200 characters)",
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Title can only contain letters, numbers, spaces, hyphens, underscores, and dots.",
                                regex="^[a-zA-Z0-9\\s\\-_\\.]+$",
                            )
                        ],
                        verbose_name="Video Title",
                    ),
                ),
                (
                    "recorded_on",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Date and time when the video was recorded",
                        validators=[
                            ndas.custom_codes.validators.validate_recording_date
                        ],
                        verbose_name="Recorded On",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the video content",
                        verbose_name="Description",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_added",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "last_edit_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_edited",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Edited By",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient associated with this video",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_files",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "ordering": ["-recorded_on"],
            },
        ),
    ]
