# Generated by Django 4.2.16 on 2025-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for easy searching', max_length=500, verbose_name='Tags'),
        ),
    ]
