# Generated by Django 4.1.6 on 2025-08-27 04:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ndas.custom_codes.validators


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_gmassessment_video_file_delete_video"),
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={
                "ordering": ["-recorded_on", "-created_at"],
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
            },
        ),
        migrations.AddField(
            model_name="video",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Video duration in seconds",
                null=True,
                validators=[django.core.validators.MaxValueValidator(14400)],
                verbose_name="Duration (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="file_size_bytes",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="File size in bytes",
                null=True,
                verbose_name="File Size (bytes)",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="height",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Video height in pixels",
                null=True,
                verbose_name="Height",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="is_assessment_ready",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this video is ready for medical assessment",
                verbose_name="Assessment Ready",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                help_text="Current processing status of the video",
                max_length=20,
                verbose_name="Processing Status",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="width",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Video width in pixels",
                null=True,
                verbose_name="Width",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient associated with this video",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                db_index=True,
                help_text="Upload the video file here",
                upload_to="videos/%Y/%m/",
                validators=[ndas.custom_codes.validators.validate_video_file],
                verbose_name="Video File",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["patient", "-recorded_on"],
                name="video_video_patient_0268ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["processing_status", "-created_at"],
                name="video_video_process_38a253_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["is_assessment_ready", "-recorded_on"],
                name="video_video_is_asse_21ed86_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="video",
            constraint=models.UniqueConstraint(
                fields=("patient", "recorded_on", "title"),
                name="unique_video_per_patient_time_title",
            ),
        ),
    ]
