# Generated by Django 4.1.6 on 2025-08-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0002_alter_video_options_video_duration_seconds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Upload"),
                    ("uploading", "Uploading"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                help_text="Current processing status of the video",
                max_length=20,
                verbose_name="Processing Status",
            ),
        ),
    ]
