# Generated by Django 4.1.6 on 2025-09-28 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0003_alter_video_processing_status"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="video",
            name="video_video_process_38a253_idx",
        ),
        migrations.RemoveIndex(
            model_name="video",
            name="video_video_is_asse_21ed86_idx",
        ),
        migrations.RemoveField(
            model_name="video",
            name="height",
        ),
        migrations.RemoveField(
            model_name="video",
            name="is_assessment_ready",
        ),
        migrations.RemoveField(
            model_name="video",
            name="processing_status",
        ),
        migrations.RemoveField(
            model_name="video",
            name="width",
        ),
    ]
