# Generated by Django 4.2.7 on 2025-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_remove_video_video_video_process_38a253_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current processing status of the video', max_length=20, verbose_name='Processing Status'),
        ),
        migrations.AddField(
            model_name='video',
            name='resolution',
            field=models.CharField(blank=True, help_text='Video resolution (e.g., 1920x1080)', max_length=20, null=True, verbose_name='Video Resolution'),
        ),
    ]
