# Generated by Django 4.1.6 on 2025-11-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0005_video_processing_status_video_resolution"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["processing_status"], name="video_processing_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["patient", "processing_status"], name="video_patient_status_idx"
            ),
        ),
    ]
