# Generated by Django 6.0 on 2026-02-24 18:10

import ndas.custom_codes.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0006_add_video_indexes"),
        ("patients", "0008_alter_diagnosislist_options_and_more"),  # Patient.institution FK required for path callable
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                db_index=True,
                help_text="Upload the video file here",
                upload_to=ndas.custom_codes.validators.get_institution_video_path,
                validators=[ndas.custom_codes.validators.validate_video_file],
                verbose_name="Video File",
            ),
        ),
    ]
